"""add_standard_embedding_phase_3

Revision ID: 890040f5f37d
Revises: cc5a5d02845b
Create Date: 2026-09-26 22:36:27.783574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '890040f5f37d'
down_revision: Union[str, Sequence[str], None] = 'cc5a5d02845b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standards', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('standards', 'embedding')
    # ### end Alembic commands ###
